package debug.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Asset implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_no
     *
     * @mbggenerated
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_item_no
     *
     * @mbggenerated
     */
    private String itemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_sub_type
     *
     * @mbggenerated
     */
    private String subType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_period_type
     *
     * @mbggenerated
     */
    private String periodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_period_count
     *
     * @mbggenerated
     */
    private Byte periodCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_product_category
     *
     * @mbggenerated
     */
    private String productCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_cmdb_product_number
     *
     * @mbggenerated
     */
    private String cmdbProductNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_create_at
     *
     * @mbggenerated
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_grant_at
     *
     * @mbggenerated
     */
    private Date grantAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_effect_at
     *
     * @mbggenerated
     */
    private Date effectAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_actual_grant_at
     *
     * @mbggenerated
     */
    private Date actualGrantAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_due_at
     *
     * @mbggenerated
     */
    private Date dueAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_payoff_at
     *
     * @mbggenerated
     */
    private Date payoffAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_update_at
     *
     * @mbggenerated
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_from_system
     *
     * @mbggenerated
     */
    private String fromSystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_principal_amount
     *
     * @mbggenerated
     */
    private Long principalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_granted_principal_amount
     *
     * @mbggenerated
     */
    private Long grantedPrincipalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_loan_channel
     *
     * @mbggenerated
     */
    private String loanChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_alias_name
     *
     * @mbggenerated
     */
    private String aliasName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_interest_amount
     *
     * @mbggenerated
     */
    private Long interestAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_fee_amount
     *
     * @mbggenerated
     */
    private Long feeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_balance_amount
     *
     * @mbggenerated
     */
    private Long balanceAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_repaid_amount
     *
     * @mbggenerated
     */
    private Long repaidAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_total_amount
     *
     * @mbggenerated
     */
    private Long totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_version
     *
     * @mbggenerated
     */
    private Short version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset.asset_interest_rate
     *
     * @mbggenerated
     */
    private BigDecimal interestRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table asset
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_id
     *
     * @return the value of asset.asset_id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_id
     *
     * @param id the value for asset.asset_id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_no
     *
     * @return the value of asset.asset_no
     *
     * @mbggenerated
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_no
     *
     * @param no the value for asset.asset_no
     *
     * @mbggenerated
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_item_no
     *
     * @return the value of asset.asset_item_no
     *
     * @mbggenerated
     */
    public String getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_item_no
     *
     * @param itemNo the value for asset.asset_item_no
     *
     * @mbggenerated
     */
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_type
     *
     * @return the value of asset.asset_type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_type
     *
     * @param type the value for asset.asset_type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_sub_type
     *
     * @return the value of asset.asset_sub_type
     *
     * @mbggenerated
     */
    public String getSubType() {
        return subType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_sub_type
     *
     * @param subType the value for asset.asset_sub_type
     *
     * @mbggenerated
     */
    public void setSubType(String subType) {
        this.subType = subType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_period_type
     *
     * @return the value of asset.asset_period_type
     *
     * @mbggenerated
     */
    public String getPeriodType() {
        return periodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_period_type
     *
     * @param periodType the value for asset.asset_period_type
     *
     * @mbggenerated
     */
    public void setPeriodType(String periodType) {
        this.periodType = periodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_period_count
     *
     * @return the value of asset.asset_period_count
     *
     * @mbggenerated
     */
    public Byte getPeriodCount() {
        return periodCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_period_count
     *
     * @param periodCount the value for asset.asset_period_count
     *
     * @mbggenerated
     */
    public void setPeriodCount(Byte periodCount) {
        this.periodCount = periodCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_product_category
     *
     * @return the value of asset.asset_product_category
     *
     * @mbggenerated
     */
    public String getProductCategory() {
        return productCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_product_category
     *
     * @param productCategory the value for asset.asset_product_category
     *
     * @mbggenerated
     */
    public void setProductCategory(String productCategory) {
        this.productCategory = productCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_cmdb_product_number
     *
     * @return the value of asset.asset_cmdb_product_number
     *
     * @mbggenerated
     */
    public String getCmdbProductNumber() {
        return cmdbProductNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_cmdb_product_number
     *
     * @param cmdbProductNumber the value for asset.asset_cmdb_product_number
     *
     * @mbggenerated
     */
    public void setCmdbProductNumber(String cmdbProductNumber) {
        this.cmdbProductNumber = cmdbProductNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_create_at
     *
     * @return the value of asset.asset_create_at
     *
     * @mbggenerated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_create_at
     *
     * @param createAt the value for asset.asset_create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_grant_at
     *
     * @return the value of asset.asset_grant_at
     *
     * @mbggenerated
     */
    public Date getGrantAt() {
        return grantAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_grant_at
     *
     * @param grantAt the value for asset.asset_grant_at
     *
     * @mbggenerated
     */
    public void setGrantAt(Date grantAt) {
        this.grantAt = grantAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_effect_at
     *
     * @return the value of asset.asset_effect_at
     *
     * @mbggenerated
     */
    public Date getEffectAt() {
        return effectAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_effect_at
     *
     * @param effectAt the value for asset.asset_effect_at
     *
     * @mbggenerated
     */
    public void setEffectAt(Date effectAt) {
        this.effectAt = effectAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_actual_grant_at
     *
     * @return the value of asset.asset_actual_grant_at
     *
     * @mbggenerated
     */
    public Date getActualGrantAt() {
        return actualGrantAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_actual_grant_at
     *
     * @param actualGrantAt the value for asset.asset_actual_grant_at
     *
     * @mbggenerated
     */
    public void setActualGrantAt(Date actualGrantAt) {
        this.actualGrantAt = actualGrantAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_due_at
     *
     * @return the value of asset.asset_due_at
     *
     * @mbggenerated
     */
    public Date getDueAt() {
        return dueAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_due_at
     *
     * @param dueAt the value for asset.asset_due_at
     *
     * @mbggenerated
     */
    public void setDueAt(Date dueAt) {
        this.dueAt = dueAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_payoff_at
     *
     * @return the value of asset.asset_payoff_at
     *
     * @mbggenerated
     */
    public Date getPayoffAt() {
        return payoffAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_payoff_at
     *
     * @param payoffAt the value for asset.asset_payoff_at
     *
     * @mbggenerated
     */
    public void setPayoffAt(Date payoffAt) {
        this.payoffAt = payoffAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_update_at
     *
     * @return the value of asset.asset_update_at
     *
     * @mbggenerated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_update_at
     *
     * @param updateAt the value for asset.asset_update_at
     *
     * @mbggenerated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_from_system
     *
     * @return the value of asset.asset_from_system
     *
     * @mbggenerated
     */
    public String getFromSystem() {
        return fromSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_from_system
     *
     * @param fromSystem the value for asset.asset_from_system
     *
     * @mbggenerated
     */
    public void setFromSystem(String fromSystem) {
        this.fromSystem = fromSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_status
     *
     * @return the value of asset.asset_status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_status
     *
     * @param status the value for asset.asset_status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_principal_amount
     *
     * @return the value of asset.asset_principal_amount
     *
     * @mbggenerated
     */
    public Long getPrincipalAmount() {
        return principalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_principal_amount
     *
     * @param principalAmount the value for asset.asset_principal_amount
     *
     * @mbggenerated
     */
    public void setPrincipalAmount(Long principalAmount) {
        this.principalAmount = principalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_granted_principal_amount
     *
     * @return the value of asset.asset_granted_principal_amount
     *
     * @mbggenerated
     */
    public Long getGrantedPrincipalAmount() {
        return grantedPrincipalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_granted_principal_amount
     *
     * @param grantedPrincipalAmount the value for asset.asset_granted_principal_amount
     *
     * @mbggenerated
     */
    public void setGrantedPrincipalAmount(Long grantedPrincipalAmount) {
        this.grantedPrincipalAmount = grantedPrincipalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_loan_channel
     *
     * @return the value of asset.asset_loan_channel
     *
     * @mbggenerated
     */
    public String getLoanChannel() {
        return loanChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_loan_channel
     *
     * @param loanChannel the value for asset.asset_loan_channel
     *
     * @mbggenerated
     */
    public void setLoanChannel(String loanChannel) {
        this.loanChannel = loanChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_alias_name
     *
     * @return the value of asset.asset_alias_name
     *
     * @mbggenerated
     */
    public String getAliasName() {
        return aliasName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_alias_name
     *
     * @param aliasName the value for asset.asset_alias_name
     *
     * @mbggenerated
     */
    public void setAliasName(String aliasName) {
        this.aliasName = aliasName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_interest_amount
     *
     * @return the value of asset.asset_interest_amount
     *
     * @mbggenerated
     */
    public Long getInterestAmount() {
        return interestAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_interest_amount
     *
     * @param interestAmount the value for asset.asset_interest_amount
     *
     * @mbggenerated
     */
    public void setInterestAmount(Long interestAmount) {
        this.interestAmount = interestAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_fee_amount
     *
     * @return the value of asset.asset_fee_amount
     *
     * @mbggenerated
     */
    public Long getFeeAmount() {
        return feeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_fee_amount
     *
     * @param feeAmount the value for asset.asset_fee_amount
     *
     * @mbggenerated
     */
    public void setFeeAmount(Long feeAmount) {
        this.feeAmount = feeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_balance_amount
     *
     * @return the value of asset.asset_balance_amount
     *
     * @mbggenerated
     */
    public Long getBalanceAmount() {
        return balanceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_balance_amount
     *
     * @param balanceAmount the value for asset.asset_balance_amount
     *
     * @mbggenerated
     */
    public void setBalanceAmount(Long balanceAmount) {
        this.balanceAmount = balanceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_repaid_amount
     *
     * @return the value of asset.asset_repaid_amount
     *
     * @mbggenerated
     */
    public Long getRepaidAmount() {
        return repaidAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_repaid_amount
     *
     * @param repaidAmount the value for asset.asset_repaid_amount
     *
     * @mbggenerated
     */
    public void setRepaidAmount(Long repaidAmount) {
        this.repaidAmount = repaidAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_total_amount
     *
     * @return the value of asset.asset_total_amount
     *
     * @mbggenerated
     */
    public Long getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_total_amount
     *
     * @param totalAmount the value for asset.asset_total_amount
     *
     * @mbggenerated
     */
    public void setTotalAmount(Long totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_version
     *
     * @return the value of asset.asset_version
     *
     * @mbggenerated
     */
    public Short getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_version
     *
     * @param version the value for asset.asset_version
     *
     * @mbggenerated
     */
    public void setVersion(Short version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset.asset_interest_rate
     *
     * @return the value of asset.asset_interest_rate
     *
     * @mbggenerated
     */
    public BigDecimal getInterestRate() {
        return interestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset.asset_interest_rate
     *
     * @param interestRate the value for asset.asset_interest_rate
     *
     * @mbggenerated
     */
    public void setInterestRate(BigDecimal interestRate) {
        this.interestRate = interestRate;
    }
}